---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 叶子.
--- DateTime: 2020/9/2 22:34
---

local json = require("cjson.safe")

function access(config)
    kong.log.info(json.encode(config))
end

return access