---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 叶子.
--- DateTime: 2020/8/31 0:00
---

return {
    name = "my-custom-plugin",
    fields = {
        {
            config = {
                type = "record",
                fields = {
                    { some_boolean = { type = "boolean", required = true, default = true } },
                    { some_set = { type = "set", required = true, elements = { type = "string", one_of = { "GET", "POST" } } } },
                    { some_array = { type = "array", elements = { type = "string", one_of = { "GET", "POST" } } } },
                    { some_string = { type = "string", required = true, default = "string", len_min = 3, len_max = 10 } },
                    { some_integer = { type = "integer", required = true, default = 6, gt = 5 } },
                    { some_number = { type = "number", required = true, default = 7.0, gt = 5.0 } },
                    {
                        some_record = {
                            type = "record",
                            fields = {
                                { key1 = { type = "string", required = true } },
                                { key2 = { type = "integer", required = true } },
                                { key3 = { type = "number", required = true } },
                            }
                        }
                    },
                }
            }
        }
    }
}